const { Command } = require("discord-akairo")

class Copypasta extends Command {
    constructor() {
        super("copypasta", {
            aliases: ["copypasta"],
            args: [
                {
                    id: "choice",
                    match: "content"
                }
            ]
        })
    }

    exec(message, args) {
        if (!args.choice) return message.reply("please include one of the following choices: \`socks\`, \`english\`, \`seals\`, \`cars\`, \`africa\`, \`phineas\`, \`confederate\`, \`shapiro\`, \`reverse\`")

        if (args.choice == "socks") {
            return message.channel.send("Alright so essentially socks are a gay insulator. When you kiss another man, touch balls, and then proceed to not say no homo. That some gay shit. Although socks are like a last line of defense. Now as I presume many of you know by now the gay travels through the ground like a current. So when you kiss another man, touch balls, and then proceed to not say no homo it doesn't go from mouth to mouth. Rather it goes down through the ground and travels up into your body from below which is GAY as FUCK. Although socks will block the gay from even entering your body thereby meaning that kissing another man, touching balls, and saying full homo are actually straight as fuck as long as you wear socks.")
        } else if (args.choice == "english") {
            return message.channel.send("I suggest you not to would you like to be called with other languages are dumber in English than in some languages, it does not matter would be to blame on the English language, for example (sry if I'm not good in English, etc.) That would be rude and mean to other people because you don't blame on different countries? I always not to judge people than to be the different language. I don't waste time being an argument of knowledge of the English language. \nWhat's the point about you think I'm only American for real life? I've worse seen have about you're talking about judging from English. I have no idea what's wrong with you about I can know the joke about speechless people doesn't mean me about somebody. Why am I only wasting time about understood English? Also, you're pointing about American English why about learning regarding does matter? They are thinking about I'm dumber than a different language? Why it is does didn't matter about English doesn't care to judge like others people.")
        } else if (args.choice == "seals") {
            return message.channel.send("What the fuck did you just fucking say about me, you little bitch? I’ll have you know I graduated top of my class in the Navy Seals, and I’ve been involved in numerous secret raids on Al-Quaeda, and I have over 300 confirmed kills. I am trained in gorilla warfare and I’m the top sniper in the entire US armed forces. You are nothing to me but just another target. I will wipe you the fuck out with precision the likes of which has never been seen before on this Earth, mark my fucking words. You think you can get away with saying that shit to me over the Internet? Think again, fucker. As we speak I am contacting my secret network of spies across the USA and your IP is being traced right now so you better prepare for the storm, maggot. The storm that wipes out the pathetic little thing you call your life. You’re fucking dead, kid. I can be anywhere, anytime, and I can kill you in over seven hundred ways, and that’s just with my bare hands. Not only am I extensively trained in unarmed combat, but I have access to the entire arsenal of the United States Marine Corps and I will use it to its full extent to wipe your miserable ass off the face of the continent, you little shit. If only you could have known what unholy retribution your little “clever” comment was about to bring down upon you, maybe you would have held your fucking tongue. But you couldn’t, you didn’t, and now you’re paying the price, you goddamn idiot. I will shit fury all over you and you will drown in it. You’re fucking dead, kiddo.")
        } else if (args.choice == "cars") {
            return message.channel.send("Ok, this is ABSOLUTE fucking bullshit. I went to see Cars in the theater yesterday, and when Lightning McQueen got HOT with Sally in Radiator Springs, my boner engaged. When Lightning McQueen said \"Ka-Chow!\", I couldn't help it!!! I closed my eyes, and I TORE my dick to shreds, using whip like motions and pulled with great force. That was one of the best nuts I ever had, just thinking about it now gets me riled up. Thing is, I nutted all over the kid sitting right next to me, and his mom got all pissed at me, screaming at me for jacking off on her son. I told that bitch to shut the fuck up, and that jacking off is a natural, artistic, and beautiful process. You should BE HAPPY that my semen is all over your son, maybe he can learn a lesson or two about the culture and art of jacking off. HOWEVER, the movie theater managers didn't agree with me. They KICKED ME OUT of the movie theater, and I didn't even finish watching the Cars movie. Not only THAT, but they made me clean up my semen after it already dried out and solidified on the seats. THATS TORTURE!! Do you know how hard it is to clean semen after its dried out? You CLEAN semen after its FRESH out of your cock, not an hour after you fucking nutted. This is a fucking OUTRAGE. Do you really expect me to not whip out my cock and jack off when i see a HOT sex scene in a movie? Either don't ban sex scenes in movies, or LET ME jack off in your theater, assholes.")
        } else if (args.choice == "africa") {
            return message.channel.send("Guys I really messed up. It all started one day when I was masturbating and crying myself to sleep. After I finished, I thought I’d just play my favorite song to cheer me up. As I played Africa, nothing seemed too unusual, so I decided to do it again the next day. This time the song just sounded a little better than the day before, and I decided that this would be my “nut song.” After a month, I would orgasm again just hearing the song. And not too far later, I just started directly masturbating to the sweet music. It started to get out of control. I would hear the song in public and have to rush home to change my pants. My nut has grown so strong that it is damaging my clothes and my parents are getting suspicious. I’m just afraid that somehow the next time I get intimate with my dog the song will come on and he will get hurt. But I guess we don’t call him “Spot” for nothing.")
        } else if (args.choice == "phineas") {
            return message.channel.send("there's 104 days 'til my self-mutilation\nand I'm so done trying to extend it\nso the annual problem of our generation\nis finding a good way to end it\n**LIKE MAYBE**\nBuilding some guillotines, commiting seppuku\nOr jumping off the Eiffel Tower\nDiscovering something that doesn't exist (MY WILL TO LIVE!)\nOr giving myself a bleach shower\nSurfing tidal waves\nCreating Ebola\nOr shooting yourself in the brain (Through the ear!)\nFinding a bomber vest\nPainting the railroad red\nOr driving a knife through your veins! (PHINEAS!)\nAs you can see\nthere's a whole lot of ways to go\nAnd I feel nothing at all.\nSo stick with us cause Phineas and Ferb are gonna end it all!\nSo stick with us cause phineas and ferb are gonna\n**END IT ALL**")
        } else if (args.choice == "confederate") {
            return message.channel.send("Holy fucking shit. I want to bang the confederate flag so goddamn bad. I can't stand it anymore. Every time I go to the town square I get a massive erection. I've seen literally every rule 34 post there is of it online. My dreams are nothing but constant fucking sex with the stars and bars. I'm sick of waking up every morning with six nuts in my boxers and knowing that those are nuts that should've been busted inside of the rebel flag's tight cloth pussy. I want it to have my mutant human/flag babies. \nFuck, my fucking mom caught me with the neighbors one. I'd dressed it in my sister\'s skirt and went to fucking town. She hasn\'t said a word to me in 10 hours and I\'m worried she\'s gonna take away my flagpole. I might not ever get to see the stars and bars again.")
        } else if (args.choice == "shapiro") {
            return message.channel.send("Holy fucking shit. I want to bang Ben Shapiro so goddamn bad. I can't stand it anymore. Every time I go to Turning Point USA I get a massive erection. I've seen literally every rule 34 post there is of him online. My dreams are nothing but constant fucking sex with Ben Shapiro. I'm sick of waking up every morning with six nuts in my boxers and knowing that those are nuts that should've been busted inside of Ben's tight conservative boi pussy. I want him to have my mutant human/conservative babies.\n\nFuck, my fucking libtard mom caught me with Ben Shapiro. I'd dressed him in my sister's skirt and went to fucking town. She hasn't said a word to me in 10 hours and I'm worried she's gonna take away my Fox News subscription. I might not ever get to see Ben Shapiro again.")
        } else if (args.choice == "reverse") {
            return message.channel.send("⠐⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠂\n⠄⠄⣰⣾⣿⣿⣿⠿⠿⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣆⠄⠄ \n⠄⠄⣿⣿⣿⡿⠋⠄⡀⣿⣿⣿⣿⣿⣿⣿⣿⠿⠛⠋⣉⣉⣉⡉⠙⠻⣿⣿⠄⠄ \n⠄⠄⣿⣿⣿⣇⠔⠈⣿⣿⣿⣿⣿⡿⠛⢉⣤⣶⣾⣿⣿⣿⣿⣿⣿⣦⡀⠹⠄⠄ \n⠄⠄⣿⣿⠃⠄⢠⣾⣿⣿⣿⠟⢁⣠⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡄⠄⠄ \n⠄⠄⣿⣿⣿⣿⣿⣿⣿⠟⢁⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⠄⠄\n⠄⠄⣿⣿⣿⣿⣿⡟⠁⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠄⠄\n⠄⠄⣿⣿⣿⣿⠋⢠⣾⣿⣿⣿⣿⣿⣿⡿⠿⠿⠿⠿⣿⣿⣿⣿⣿⣿⣿⣿⠄⠄\n⠄⠄⣿⣿⡿⠁⣰⣿⣿⣿⣿⣿⣿⣿⣿⠗⠄⠄⠄⠄⣿⣿⣿⣿⣿⣿⣿⡟⠄⠄\n⠄⠄⣿⡿⠁⣼⣿⣿⣿⣿⣿⣿⡿⠋⠄⠄⠄⣠⣄⢰⣿⣿⣿⣿⣿⣿⣿⠃⠄⠄ \n⠄⠄⡿⠁⣼⣿⣿⣿⣿⣿⣿⣿⡇⠄⢀⡴⠚⢿⣿⣿⣿⣿⣿⣿⣿⣿⡏⢠⠄⠄ \n⠄⠄⠃⢰⣿⣿⣿⣿⣿⣿⡿⣿⣿⠴⠋⠄⠄⢸⣿⣿⣿⣿⣿⣿⣿⡟⢀⣾⠄⠄\n⠄⠄⢀⣿⣿⣿⣿⣿⣿⣿⠃⠈⠁⠄⠄⢀⣴⣿⣿⣿⣿⣿⣿⣿⡟⢀⣾⣿⠄⠄\n⠄⠄⢸⣿⣿⣿⣿⣿⣿⣿⠄⠄⠄⠄⢶⣿⣿⣿⣿⣿⣿⣿⣿⠏⢀⣾⣿⣿⠄⠄ \n⠄⠄⣿⣿⣿⣿⣿⣿⣿⣷⣶⣶⣶⣶⣶⣿⣿⣿⣿⣿⣿⣿⠋⣠⣿⣿⣿⣿⠄⠄ \n⠄⠄⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠟⢁⣼⣿⣿⣿⣿⣿⠄⠄ \n⠄⠄⢻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠟⢁⣴⣿⣿⣿⣿⣿⣿⣿⠄⠄ \n⠄⠄⠈⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠟⢁⣴⣿⣿⣿⣿⠗⠄⠄⣿⣿⠄⠄ \n⠄⠄⣆⠈⠻⢿⣿⣿⣿⣿⣿⣿⠿⠛⣉⣤⣾⣿⣿⣿⣿⣿⣇⠠⠺⣷⣿⣿⠄⠄ \n⠄⠄⣿⣿⣦⣄⣈⣉⣉⣉⣡⣤⣶⣿⣿⣿⣿⣿⣿⣿⣿⠉⠁⣀⣼⣿⣿⣿⠄⠄\n⠄⠄⠻⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣶⣾⣿⣿⡿⠟⠄⠄\n⠠⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄")
        } else {
            return message.reply("inavlid choice. Please include one of the following choices: \`socks\`, \`english\`, \`seals\`, \`cars\`, \`africa\`, \`phineas\`, \`confederate\`, \`shapiro\`, \`reverse\`")
        }
    }
}

module.exports = Copypasta